// ─── M4 Community Mock Data ──────────────────────────────────────────────────

export interface KnowledgeArticle {
  id: string
  title: string
  category: string
  tags: string[]
  author: string
  authorAvatar: string
  views: number
  likes: number
  comments: number
  createdAt: string
  updatedAt: string
  content: string
  isPinned: boolean
  isFeatured: boolean
  readTime: number
}

export interface DiscussionPost {
  id: string
  title: string
  content: string
  author: string
  authorAvatar: string
  authorRole: string
  tags: string[]
  views: number
  likes: number
  replies: number
  createdAt: string
  lastActivity: string
  isPinned: boolean
  isSolved: boolean
  trending: boolean
}

export interface CommunityEvent {
  id: string
  title: string
  type: 'webinar' | 'workshop' | 'meetup' | 'conference' | 'hackathon'
  status: 'upcoming' | 'live' | 'ended' | 'open'
  date: string
  time: string
  duration: string
  attendees: number
  maxAttendees?: number
  host: string
  hostAvatar: string
  platform: string
  description: string
  tags: string[]
  registered: number
  featured: boolean
}

export interface TalentProfile {
  id: string
  name: string
  avatar: string
  title: string
  company: string
  skills: string[]
  availability: 'available' | 'busy' | 'unavailable'
  hourlyRate?: number
  rating: number
  completedProjects: number
  bio: string
  location: string
  joinedAt: string
  badges: string[]
  responseRate: number
}

// ─── Knowledge Base Articles ────────────────────────────────────────────────

export const MOCK_KB_ARTICLES: KnowledgeArticle[] = [
  {
    id: 'kb-001',
    title: '蔚蓝 OPC 平台快速入门完全指南（2026最新版）',
    category: '入门指南',
    tags: ['新手指南', '基础操作', '平台介绍'],
    author: '小蓝',
    authorAvatar: 'https://picsum.photos/seed/kbauth1/100/100',
    views: 45230,
    likes: 3420,
    comments: 287,
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-05-01T14:30:00Z',
    content: '本文将详细介绍蔚蓝 OPC 平台的核心功能与使用技巧，帮助新用户快速上手...',
    isPinned: true,
    isFeatured: true,
    readTime: 12,
  },
  {
    id: 'kb-002',
    title: 'AI 运营 Agent 实战：如何用 M1 模块实现自动化内容生产',
    category: '进阶技巧',
    tags: ['AI运营', 'Agent', '自动化', 'M1模块'],
    author: 'Tech船长',
    authorAvatar: 'https://picsum.photos/seed/kbauth2/100/100',
    views: 28940,
    likes: 2150,
    comments: 198,
    createdAt: '2026-02-20T11:00:00Z',
    updatedAt: '2026-04-28T10:00:00Z',
    content: '深入解析 M1 模块的 AI Agent 能力，实现日产1000条内容的自动化流水线...',
    isPinned: false,
    isFeatured: true,
    readTime: 18,
  },
  {
    id: 'kb-003',
    title: 'M2 市场对接：品牌方与服务商的高效匹配策略',
    category: '市场对接',
    tags: ['M2模块', '品牌对接', '服务商', '匹配策略'],
    author: '莉莉安',
    authorAvatar: 'https://picsum.photos/seed/kbauth3/100/100',
    views: 18760,
    likes: 1560,
    comments: 143,
    createdAt: '2026-03-05T15:30:00Z',
    updatedAt: '2026-05-10T09:00:00Z',
    content: '品牌方如何在 M2 市场找到最合适的运营服务商？本文分享5个高效匹配策略...',
    isPinned: false,
    isFeatured: false,
    readTime: 10,
  },
  {
    id: 'kb-004',
    title: '内容安全合规：各大平台审核规则对比与应对方案',
    category: '合规运营',
    tags: ['内容合规', '平台审核', '风险管理', '合规运营'],
    author: '合规老周',
    authorAvatar: 'https://picsum.photos/seed/kbauth4/100/100',
    views: 32450,
    likes: 2890,
    comments: 312,
    createdAt: '2026-03-18T10:00:00Z',
    updatedAt: '2026-05-12T16:00:00Z',
    content: '微信、抖音、小红书、微博各平台的内容审核规则有何不同？如何规避违规风险...',
    isPinned: false,
    isFeatured: true,
    readTime: 15,
  },
  {
    id: 'kb-005',
    title: '私域流量运营全攻略：从引流到转化的完整闭环',
    category: '私域运营',
    tags: ['私域流量', '用户运营', '转化', '增长黑客'],
    author: '增长官阿杰',
    authorAvatar: 'https://picsum.photos/seed/kbauth5/100/100',
    views: 56780,
    likes: 4560,
    comments: 421,
    createdAt: '2026-04-01T08:00:00Z',
    updatedAt: '2026-05-15T11:30:00Z',
    content: '私域流量是当前最核心的资产之一，本文手把手教你从0到1搭建私域运营体系...',
    isPinned: false,
    isFeatured: true,
    readTime: 22,
  },
  {
    id: 'kb-006',
    title: '数据分析实战：用仪表盘洞察运营全局',
    category: '数据运营',
    tags: ['数据分析', '仪表盘', '运营洞察', '数据驱动'],
    author: '数据星探',
    authorAvatar: 'https://picsum.photos/seed/kbauth6/100/100',
    views: 21340,
    likes: 1780,
    comments: 156,
    createdAt: '2026-04-15T13:00:00Z',
    updatedAt: '2026-05-08T10:00:00Z',
    content: '通过 OPC 平台的数据仪表盘，如何快速定位运营问题并制定优化策略...',
    isPinned: false,
    isFeatured: false,
    readTime: 14,
  },
  {
    id: 'kb-007',
    title: '618大促运营作战手册：选品、投放、复盘全流程',
    category: '大促专题',
    tags: ['618', '大促', '选品', '投放', '复盘'],
    author: '大促操盘手',
    authorAvatar: 'https://picsum.photos/seed/kbauth7/100/100',
    views: 68920,
    likes: 5890,
    comments: 534,
    createdAt: '2026-04-20T09:00:00Z',
    updatedAt: '2026-05-16T08:00:00Z',
    content: '一年一度的618大促即将来临，本文提供完整的作战手册，涵盖选品、投放、客服、复盘全链路...',
    isPinned: false,
    isFeatured: true,
    readTime: 25,
  },
  {
    id: 'kb-008',
    title: '跨平台内容分发：一次创作、多点投放的高效方法论',
    category: '内容运营',
    tags: ['内容分发', '跨平台', '效率工具', '创作方法论'],
    author: '内容架构师小林',
    authorAvatar: 'https://picsum.photos/seed/kbauth8/100/100',
    views: 15670,
    likes: 1230,
    comments: 98,
    createdAt: '2026-04-28T11:00:00Z',
    updatedAt: '2026-05-14T15:00:00Z',
    content: '如何用 OPC 的 M3 创作中心实现一次创作、自动适配、多平台高效分发...',
    isPinned: false,
    isFeatured: false,
    readTime: 11,
  },
]

// ─── Discussion Posts ────────────────────────────────────────────────────────

export const MOCK_DISCUSSIONS: DiscussionPost[] = [
  {
    id: 'disc-001',
    title: 'AI 生成的内容在各大平台容易被识别吗？如何降低被限流风险？',
    content: '最近用 AI 工具批量生成内容发布，但发现部分平台开始识别 AI 痕迹，导致内容被限流。大家有什么好的应对策略吗？比如在 AI 生成内容基础上做人工润色的比例是多少合适？',
    author: '运营小白阿涛',
    authorAvatar: 'https://picsum.photos/seed/disc1/100/100',
    authorRole: '运营新人',
    tags: ['AI内容', '平台限流', '内容优化'],
    views: 8920,
    likes: 456,
    replies: 89,
    createdAt: '2026-05-05T14:00:00Z',
    lastActivity: '2026-05-06T09:30:00Z',
    isPinned: false,
    isSolved: true,
    trending: true,
  },
  {
    id: 'disc-002',
    title: '【经验分享】我是如何在3个月内把私域粉丝从0做到10万的',
    content: '去年下半年开始做私域运营，从零开始摸索，到现在累计了10万+精准粉丝。分享一下我的完整路径和踩过的坑，希望能帮到大家。',
    author: '私域增长达人小鱼',
    authorAvatar: 'https://picsum.photos/seed/disc2/100/100',
    authorRole: '私域操盘手',
    tags: ['私域增长', '经验分享', '粉丝积累'],
    views: 24560,
    likes: 2340,
    replies: 187,
    createdAt: '2026-04-28T10:00:00Z',
    lastActivity: '2026-05-06T11:00:00Z',
    isPinned: true,
    isSolved: false,
    trending: true,
  },
  {
    id: 'disc-003',
    title: 'M2 市场的服务商质量参差不齐，有什么筛选标准吗？',
    content: '最近在 M2 市场找代运营服务商，联系了几家但感觉质量差异很大。想问问大家有没有什么筛选标准或者评估维度可以参考？',
    author: '品牌负责人小方',
    authorAvatar: 'https://picsum.photos/seed/disc3/100/100',
    authorRole: '品牌方',
    tags: ['M2市场', '服务商筛选', '代运营'],
    views: 5670,
    likes: 320,
    replies: 67,
    createdAt: '2026-05-03T16:30:00Z',
    lastActivity: '2026-05-06T08:45:00Z',
    isPinned: false,
    isSolved: false,
    trending: false,
  },
  {
    id: 'disc-004',
    title: '抖音直播数据下滑，帮忙分析下是什么原因？',
    content: '我们账号之前场均观看能到5000+，最近几场只有2000左右。内容形式和投放策略都没怎么变，但数据就是上不去。有没有大佬帮忙看看可能是什么问题？',
    author: '直播运营小明',
    authorAvatar: 'https://picsum.photos/seed/disc4/100/100',
    authorRole: '直播运营',
    tags: ['抖音直播', '数据分析', '流量下滑', '问题诊断'],
    views: 7840,
    likes: 210,
    replies: 54,
    createdAt: '2026-05-04T20:00:00Z',
    lastActivity: '2026-05-06T10:15:00Z',
    isPinned: false,
    isSolved: false,
    trending: true,
  },
  {
    id: 'disc-005',
    title: '端午节营销活动方案交流，大家有什么创意？',
    content: '今年端午节想做一个系列营销活动，但创意方面有点瓶颈。大家有没有什么新颖的活动思路？除了常规的优惠折扣，有什么能真正打动用户的玩法？',
    author: '营销策划小七',
    authorAvatar: 'https://picsum.photos/seed/disc5/100/100',
    authorRole: '营销策划',
    tags: ['端午节', '营销活动', '创意策划'],
    views: 4560,
    likes: 380,
    replies: 78,
    createdAt: '2026-05-06T09:00:00Z',
    lastActivity: '2026-05-06T12:00:00Z',
    isPinned: false,
    isSolved: false,
    trending: false,
  },
  {
    id: 'disc-006',
    title: '揭露一个在 M2 市场遇到的骗子服务商，大家注意防范',
    content: '4月份在 M2 市场遇到一个服务商，前期沟通很积极，收了定金后就消失了。希望大家引以为戒，交易时注意核实对方资质。',
    author: '防骗志愿者老王',
    authorAvatar: 'https://picsum.photos/seed/disc6/100/100',
    authorRole: '社区志愿者',
    tags: ['防骗指南', 'M2市场', '安全交易'],
    views: 18920,
    likes: 1560,
    replies: 234,
    createdAt: '2026-05-02T11:00:00Z',
    lastActivity: '2026-05-06T07:30:00Z',
    isPinned: true,
    isSolved: true,
    trending: false,
  },
  {
    id: 'disc-007',
    title: '微信视频号和抖音的内容策略有什么本质区别？',
    content: '同时运营视频号和抖音，但感觉用同一套内容效果差异很大。想请教一下两个平台的用户偏好和内容策略有什么本质不同？',
    author: '多平台运营阿鹏',
    authorAvatar: 'https://picsum.photos/seed/disc7/100/100',
    authorRole: '运营老兵',
    tags: ['视频号', '抖音', '内容策略', '多平台运营'],
    views: 11230,
    likes: 890,
    replies: 112,
    createdAt: '2026-04-30T15:00:00Z',
    lastActivity: '2026-05-05T22:00:00Z',
    isPinned: false,
    isSolved: true,
    trending: false,
  },
  {
    id: 'disc-008',
    title: 'OPC 平台的 AI Agent 能不能完全替代人工运营？',
    content: '看了平台新出的 AI Agent 功能很心动，但不确定实际效果。有人用 AI Agent 完全接手过某个运营环节吗？效果如何？',
    author: '观望者小张',
    authorAvatar: 'https://picsum.photos/seed/disc8/100/100',
    authorRole: '观望者',
    tags: ['AI Agent', '自动化运营', '效果讨论'],
    views: 9340,
    likes: 670,
    replies: 95,
    createdAt: '2026-05-01T10:00:00Z',
    lastActivity: '2026-05-05T18:00:00Z',
    isPinned: false,
    isSolved: false,
    trending: false,
  },
]

// ─── Community Events ────────────────────────────────────────────────────────

export const MOCK_EVENTS: CommunityEvent[] = [
  {
    id: 'evt-001',
    title: '618大促流量打法实战分享会',
    type: 'webinar',
    status: 'upcoming',
    date: '2026-05-20',
    time: '20:00',
    duration: '90分钟',
    attendees: 342,
    maxAttendees: 500,
    host: '大促导师李老师',
    hostAvatar: 'https://picsum.photos/seed/evt1/100/100',
    platform: 'Zoom',
    description: '距离618不足一个月，本次分享会邀请三位头部品牌操盘手，实战讲解流量获取、转化提升、大促复盘全链路策略。',
    tags: ['618', '大促', '流量打法', '实战分享'],
    registered: 342,
    featured: true,
  },
  {
    id: 'evt-002',
    title: 'AI 运营工具应用工作坊（第3期）',
    type: 'workshop',
    status: 'open',
    date: '2026-05-25',
    time: '14:00',
    duration: '3小时',
    attendees: 28,
    maxAttendees: 30,
    host: 'AI运营专家小林',
    hostAvatar: 'https://picsum.photos/seed/evt2/100/100',
    platform: '腾讯会议',
    description: '手把手教你用 AI 工具提升内容生产效率5倍以上，现场演示+实操练习，课后配套练习素材包。',
    tags: ['AI工具', '工作坊', '效率提升', '实操'],
    registered: 28,
    featured: true,
  },
  {
    id: 'evt-003',
    title: '蔚蓝 OPC 社区线下聚会·深圳站',
    type: 'meetup',
    status: 'upcoming',
    date: '2026-06-05',
    time: '14:00',
    duration: '4小时',
    attendees: 67,
    maxAttendees: 100,
    host: '蔚蓝社区运营组',
    hostAvatar: 'https://picsum.photos/seed/evt3/100/100',
    platform: '深圳·南山科技园',
    description: '深圳地区社区成员线下见面会，提供茶歇和精美周边，设有自由交流、项目对接、嘉宾分享等多个环节。',
    tags: ['线下聚会', '深圳', '社区交流', 'Networking'],
    registered: 67,
    featured: false,
  },
  {
    id: 'evt-004',
    title: '2026 AI 赋能品牌增长峰会',
    type: 'conference',
    status: 'upcoming',
    date: '2026-06-20',
    time: '09:00',
    duration: '全天',
    attendees: 1240,
    host: '蔚蓝科技 × 行业媒体',
    hostAvatar: 'https://picsum.photos/seed/evt4/100/100',
    platform: '深圳国际会展中心',
    description: '汇聚50+行业大咖、500+品牌决策者，围绕AI营销、私域增长、品牌出海等核心议题，输出最新行业洞察与实战方法论。',
    tags: ['AI营销', '品牌增长', '峰会', '行业大会'],
    registered: 1240,
    featured: true,
  },
  {
    id: 'evt-005',
    title: '24小时运营增长 Hackathon',
    type: 'hackathon',
    status: 'ended',
    date: '2026-04-15',
    time: '10:00',
    duration: '24小时',
    attendees: 86,
    host: '蔚蓝开发者社区',
    hostAvatar: 'https://picsum.photos/seed/evt5/100/100',
    platform: '线上+线下混合',
    description: '24小时极限创作，主题为"AI驱动运营增长"，吸引了全国200+选手报名，最终36支队伍入围。',
    tags: ['Hackathon', 'AI运营', '黑客松', '创新挑战'],
    registered: 86,
    featured: false,
  },
  {
    id: 'evt-006',
    title: '小红书爆款内容创作训练营',
    type: 'workshop',
    status: 'live',
    date: '2026-05-06',
    time: '19:00',
    duration: '2小时',
    attendees: 156,
    maxAttendees: 200,
    host: '小红书官方认证讲师@美妆笔记',
    hostAvatar: 'https://picsum.photos/seed/evt6/100/100',
    platform: '小鹅通',
    description: '官方认证讲师亲授小红书爆款内容密码，从选题策划到封面设计，从文案撰写到标签优化，系统性提升账号影响力。',
    tags: ['小红书', '爆款内容', '训练营', '官方认证'],
    registered: 156,
    featured: true,
  },
  {
    id: 'evt-007',
    title: '企业微信私域实战百人大课',
    type: 'webinar',
    status: 'ended',
    date: '2026-04-28',
    time: '20:00',
    duration: '120分钟',
    attendees: 2300,
    host: '私域架构师阿龙',
    hostAvatar: 'https://picsum.photos/seed/evt7/100/100',
    platform: '钉钉直播',
    description: '企业微信私域从0到1搭建全流程，含社群分层、自动化SOP、千人群运营等核心模块，课后可领取完整课件。',
    tags: ['企业微信', '私域运营', '社群运营', 'SOP'],
    registered: 2300,
    featured: false,
  },
  {
    id: 'evt-008',
    title: '短视频带货选品逻辑与供应链对接会',
    type: 'meetup',
    status: 'upcoming',
    date: '2026-05-30',
    time: '15:00',
    duration: '3小时',
    attendees: 45,
    maxAttendees: 80,
    host: '带货MCN机构联盟',
    hostAvatar: 'https://picsum.photos/seed/evt8/100/100',
    platform: '广州·琶洲',
    description: '聚焦短视频带货选品难题，邀请10+优质供应链到场对接，涵盖美妆、食品、数码等热门品类，支持一对一洽谈。',
    tags: ['短视频带货', '选品', '供应链', 'MCN'],
    registered: 45,
    featured: false,
  },
]

// ─── Talent Market Profiles ──────────────────────────────────────────────────

export const MOCK_TALENTS: TalentProfile[] = [
  {
    id: 'talent-001',
    name: '陈运营',
    avatar: 'https://picsum.photos/seed/talent1/100/100',
    title: '高级运营经理',
    company: '某头部MCN机构',
    skills: ['私域运营', '用户增长', '活动策划', '数据分析', '抖音运营'],
    availability: 'available',
    hourlyRate: 380,
    rating: 4.9,
    completedProjects: 124,
    bio: '8年运营经验，操盘过多个百万级账号，擅长私域搭建与转化提升。服务过元气森林、百果园等知名品牌。',
    location: '深圳',
    joinedAt: '2025-03-15',
    badges: ['TOP服务商', '极速响应', '年度精选'],
    responseRate: 98,
  },
  {
    id: 'talent-002',
    name: '林内容',
    avatar: 'https://picsum.photos/seed/talent2/100/100',
    title: '内容创意总监',
    company: '某创意公司',
    skills: ['内容策划', '短视频创作', '品牌文案', '账号定位', 'KOL对接'],
    availability: 'available',
    hourlyRate: 450,
    rating: 4.8,
    completedProjects: 89,
    bio: '前字节跳动内容运营，深度理解平台算法逻辑。主导过多个从0到1的账号孵化项目，内容播放量累计超10亿。',
    location: '北京',
    joinedAt: '2025-05-20',
    badges: ['内容专家', '爆款制造机', '极速响应'],
    responseRate: 95,
  },
  {
    id: 'talent-003',
    name: '张增长',
    avatar: 'https://picsum.photos/seed/talent3/100/100',
    title: '用户增长专家',
    company: '某SaaS公司',
    skills: ['用户增长', '裂变活动', '投放优化', 'AB测试', '数据建模'],
    availability: 'busy',
    rating: 4.7,
    completedProjects: 56,
    bio: '专注用户增长5年，擅长用数据驱动增长策略。曾在某社交产品实现月活从100万到1000万的增长。',
    location: '上海',
    joinedAt: '2025-07-10',
    badges: ['增长黑客', '数据达人'],
    responseRate: 88,
  },
  {
    id: 'talent-004',
    name: '王设计',
    avatar: 'https://picsum.photos/seed/talent4/100/100',
    title: '视觉设计师',
    company: '自由职业',
    skills: ['品牌视觉', 'UI设计', '营销素材', '视频剪辑', 'Figma'],
    availability: 'available',
    hourlyRate: 280,
    rating: 5.0,
    completedProjects: 203,
    bio: '专注品牌视觉设计6年，服务过200+品牌客户。设计作品曾获红点设计奖，擅长将品牌战略转化为视觉语言。',
    location: '杭州',
    joinedAt: '2025-02-01',
    badges: ['设计大牛', 'TOP服务商', '极速响应', '年度精选'],
    responseRate: 100,
  },
  {
    id: 'talent-005',
    name: '刘投放',
    avatar: 'https://picsum.photos/seed/talent5/100/100',
    title: '付费投放专家',
    company: '某广告代理公司',
    skills: ['巨量引擎', '腾讯广告', '信息流投放', '投放策略', 'ROI优化'],
    availability: 'available',
    hourlyRate: 350,
    rating: 4.6,
    completedProjects: 78,
    bio: '管理过年消耗500万+的投放账户，擅长效果广告优化。服务客户涵盖电商、教育、金融等多个行业。',
    location: '广州',
    joinedAt: '2025-06-25',
    badges: ['投放专家', 'ROI优化师'],
    responseRate: 92,
  },
  {
    id: 'talent-006',
    name: '赵直播',
    avatar: 'https://picsum.photos/seed/talent6/100/100',
    title: '直播运营总监',
    company: '某直播基地',
    skills: ['直播运营', '主播培训', '场控设计', '数据复盘', '供应链选品'],
    availability: 'busy',
    rating: 4.8,
    completedProjects: 45,
    bio: '操盘过单场GMV超千万的直播专场，培养过多名月销百万级别主播。深度理解直播电商全链路运营逻辑。',
    location: '上海',
    joinedAt: '2025-08-12',
    badges: ['直播大牛', 'TOP服务商'],
    responseRate: 85,
  },
  {
    id: 'talent-007',
    name: '孙数据',
    avatar: 'https://picsum.photos/seed/talent7/100/100',
    title: '数据分析师',
    company: '某科技公司',
    skills: ['Python', 'SQL', '数据可视化', 'BI工具', '用户洞察', 'AB测试'],
    availability: 'available',
    hourlyRate: 320,
    rating: 4.9,
    completedProjects: 67,
    bio: '统计学背景，专注数据分析4年。擅长用数据发现业务问题并提出可落地的优化建议，精通Python数据分析和Tableau可视化。',
    location: '成都',
    joinedAt: '2025-09-05',
    badges: ['数据专家', '极速响应'],
    responseRate: 97,
  },
  {
    id: 'talent-008',
    name: '周AI',
    avatar: 'https://picsum.photos/seed/talent8/100/100',
    title: 'AI应用工程师',
    company: '某AI创业公司',
    skills: ['AI Agent', 'Prompt工程', 'Python', 'API集成', '自动化流程', '大模型微调'],
    availability: 'available',
    hourlyRate: 420,
    rating: 4.7,
    completedProjects: 34,
    bio: '专注AI应用落地，精通各类大模型API调用与 Agent 工作流设计。帮助30+企业搭建AI自动化运营体系，平均效率提升300%。',
    location: '北京',
    joinedAt: '2026-01-20',
    badges: ['AI专家', '效率提升专家'],
    responseRate: 94,
  },
]
